[package]
name = "sht4x"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
defmt = { version = "0.3.2", optional = true }
embedded-hal = "0.2.7"
fixed = "1.20.0"
sensirion-i2c = "0.2"

[features]
defmt = ["dep:defmt"]
