[package]
name = "sht4x-ng"
description = "Sensirion SHT4x Driver for Embedded HAL 1.0 with optional async support"
version = "0.2.2"
edition = "2021"

authors = [
    "Christian Meusel <christian.meusel@posteo.de>",
    "Brian Bustin",
    "Moritz Bitsch",
]

license = "MIT OR Apache-2.0"

categories = ["embedded", "hardware-support", "no-std"]
keywords = ["driver", "embedded-hal-driver", "sensirion", "sht40"]

exclude = ["/.github/", ".gitignore"]


[dependencies]
defmt = { version = "0.3.8", optional = true }
embedded-hal = "1.0.0"
embedded-hal-async = { version = "1.0.0", optional = true }
fixed = "1.27.0"
sensirion-i2c = "0.3.0"

[features]
defmt = ["dep:defmt"]
async = ["dep:embedded-hal-async"]
