[package]
name = "sht4x"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
defmt = { version = "0.3.1", optional = true }
embedded-hal = "0.2.6"
fixed = "1.11.0"
sensirion-i2c = { git = "https://github.com/Sensirion/sensirion-i2c-rs", rev = "b89f4c5" }

[features]
defmt = ["dep:defmt"]
